export const CHANGE_LIGHT = "CHANGE_LIGHT";
export const REQUEST_CROSSING = "REQUEST_CROSSING";
export const RESET_TIMER = "RESET_TIMER";
export const EMERGENCY_OVERRIDE = "EMERGENCY_OVERRIDE";
export const START_COUNTDOWN = "START_COUNTDOWN";
